CREATE TABLE PARCEIRO(
   ID_PARCEIRO TEXT PRIMARY KEY UNIQUE NOT NULL,
   NM_PARCEIRO VARCHAR(100) NOT NULL,
   CD_USR_INCLUSAO CHAR(15) NOT NULL,
   DT_INCLUSAO TIMESTAMP NOT NULL,
   CD_USR_ATUALIZACAO CHAR(15),
   DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE PERFIL(
    ID_PERFIL SMALLINT PRIMARY KEY UNIQUE NOT NULL,
    NM_PARCEIRO VARCHAR(100) NOT NULL,
    CD_USR_INCLUSAO CHAR(15) NOT NULL,
	DT_INCLUSAO TIMESTAMP NOT NULL,
	CD_USR_ATUALIZACAO CHAR(15),
    DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE COOPERATIVA(
    ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
    CD_UNIDADE CHAR(8) NOT NULL,
	NM_UNIDADE VARCHAR(100) NOT NULL,
	CD_USR_INCLUSAO CHAR(15) NOT NULL,
	DT_INCLUSAO TIMESTAMP NOT NULL,
	CD_USR_ATUALIZACAO CHAR(15),
	DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE DADOSALLIANZ(
    ID INTEGER PRIMARY KEY UNIQUE NOT NULL,	
    CD_MEDIADOR INTEGER NOT NULL,
    DS_USUARIO_BA CHAR(8) NOT NULL
);

ALTER TABLE PERFIL ALTER COLUMN DT_INCLUSAO SET DEFAULT now();
ALTER TABLE COOPERATIVA ALTER COLUMN DT_INCLUSAO SET DEFAULT now();
ALTER TABLE PARCEIRO ALTER COLUMN DT_INCLUSAO SET DEFAULT now();

ALTER TABLE PERFIL ALTER COLUMN DT_INCLUSAO SET DEFAULT now();
ALTER TABLE COOPERATIVA ALTER COLUMN DT_INCLUSAO SET DEFAULT now();
ALTER TABLE PARCEIRO ALTER COLUMN DT_INCLUSAO SET DEFAULT now();


INSERT INTO PERFIL (ID_PERFIL, NM_PARCEIRO, CD_USR_INCLUSAO) VALUES (1, 'Partner 1', '000000000000000');
INSERT INTO PARCEIRO (ID_PARCEIRO, NM_PARCEIRO, CD_USR_INCLUSAO) VALUES(2, 'Partner 11', '000000000000000');
INSERT INTO COOPERATIVA (ID, CD_UNIDADE, NM_UNIDADE, CD_USR_INCLUSAO) VALUES(3, '00000000', 'Cooperativa 1', '000000000000000');
INSERT INTO DADOSALLIANZ (ID, CD_MEDIADOR, DS_USUARIO_BA) VALUES(1, 1, 'BBBAAACC');